-- Fix region admins who have no region_id set.
-- Run this in Supabase SQL Editor if region admins see "No branches found".
--
-- First, check which region admins need fixing:
-- SELECT id, email, full_name, role, region_id FROM public.profiles WHERE role = 'region_admin' AND region_id IS NULL;
--
-- Then assign a region (replace USER_ID and REGION_ID with actual UUIDs):
-- UPDATE public.profiles SET region_id = 'REGION_UUID' WHERE id = 'USER_ID' AND role = 'region_admin';
--
-- To list regions: SELECT id, name FROM public.regions ORDER BY name;
